apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-app-deployment
  labels:
    app: gym-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-app
  template:
    metadata:
      labels:
        app: gym-app
    spec:
      containers:
        - name: gym-app-container
          image: fadhinotgr/gym-management-system-app:latest
          imagePullPolicy: Always
          command: ["python"]
          args: ["app.py"]
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: gym-app-service
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31111
  selector:
    app: gym-app